
# CI on Windows via appveyor
# This file was based on Olivier Grisel's python-appveyor-demo

environment:

  global:
    PYTHON: "C:\\conda"
    CONDA_DEPENDENCIES: "pytest pytest-cov"
    PIP_DEPENDENCIES: "ipython"

  matrix:
    - PYTHON_VERSION: "3.5"
      PYTHON_ARCH: "64"
    - PYTHON_VERSION: "3.7"
      PYTHON_ARCH: "64"

platform:
    -x64

install:
    - "git clone git://github.com/astropy/ci-helpers.git"
    - "powershell ci-helpers/appveyor/install-miniconda.ps1"
    - "conda activate test"

build: false  # Not a C# project, build stuff at the test step instead.

test_script:
  - python setup.py develop
  - pytest pyonelab
