#!/usr/bin/env python
# -*- coding: utf-8 -*-
# Author: Benjamin Vial
# This file is part of pyonelab
# License: MIT

import sys
import subprocess
import pyonelab

subprocess.call([pyonelab.gmsh_exec_path] + sys.argv[1:])

